name: burgan_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1      # Compatible with firebase_core ^3.6.0
  cloud_firestore: ^5.4.4    # Requires firebase_core ^3.6.0
  firebase_core: ^3.6.0      # Updated to resolve conflict
  go_router: ^6.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
