// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAIAPTc_fNgzCbmKU0ACsVI8mj1TAe8k',
    appId: '1:191250449319:web:3dc613a12ff01927fe6c82',
    messagingSenderId: '191250449319',
    projectId: 'baba-f78d6',
    authDomain: 'baba-f78d6.firebaseapp.com',
    storageBucket: 'baba-f78d6.appspot.com',
    measurementId: 'G-STH6SQQRYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYEzzf9UaoUBsTdhoBSWVVwpmGN7KKZU',
    appId: '1:191250449319:android:645676da062c269efe6c82',
    messagingSenderId: '191250449319',
    projectId: 'baba-f78d6',
    storageBucket: 'baba-f78d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDE-JziarC85goDsw4-F5r4ZRpHwShy2s',
    appId: '1:191250449319:ios:da8a35648303dc73fe6c82',
    messagingSenderId: '191250449319',
    projectId: 'baba-f78d6',
    storageBucket: 'baba-f78d6.appspot.com',
    iosBundleId: 'com.example.burganApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDE-JziarC85goDsw4-F5r4ZRpHwShy2s',
    appId: '1:191250449319:ios:da8a35648303dc73fe6c82',
    messagingSenderId: '191250449319',
    projectId: 'baba-f78d6',
    storageBucket: 'baba-f78d6.appspot.com',
    iosBundleId: 'com.example.burganApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAIAPTc_fNgzCbmKU0ACsVI8mj1TAe8k',
    appId: '1:191250449319:web:6389717061003eaffe6c82',
    messagingSenderId: '191250449319',
    projectId: 'baba-f78d6',
    authDomain: 'baba-f78d6.firebaseapp.com',
    storageBucket: 'baba-f78d6.appspot.com',
    measurementId: 'G-6GJNPNMSPL',
  );
}
